cloud build: create work directory
This fixes the following cloud build failure:
  tests that need to be skipped: CSI_PROW_E2E_SKIP=Disruptive
  tar: can't change directory to '': No such file or directory
  Thu Jun 17 17:15:10 UTC 2021 go1.13.5 $ curl --fail --location https://dl.google.com/go/go1.16.linux-amd64.tar.gz
  ...
  curl: (23) Failed writing body (0 != 1377)
  ERROR: installation of Go 1.16 failed
  ERROR
  ERROR: build step 0 "gcr.io/k8s-testimages/gcb-docker-gcloud:v20200421-a2bf5f8" failed: step exited with non-zero status: 1

It's necessary because of https://github.com/kubernetes-csi/csi-release-tools/commit/6880b0c80d2c43187c8d0ce3ff61c9517a56d34d